salt-ui/saltui

- src/Datetime/utils.js
> Disabled date

- demo/ActionSheet/ActionSheetDemo.jsx
- docs/ActionSheet.md
- src/ActionSheet/ActionSheet.styl
- src/ActionSheet/Panel.jsx
- src/ActionSheet/SharePanel.jsx
> restyle ActionSheet

- demo/RadioField/RadioFieldDemo.js
- demo/RadioField/RadioFieldDemo.styl
- docs/RadioField.md
- src/RadioField/RadioField.jsx
- src/RadioField/RadioField.styl
> RadioField 新增 popup 模式

- CHANGELOG.md
- package.json
- src/Button/Button.jsx
> onClick will not called if button's loading is true

- docs/Tab.md
- src/Tab/Tab.jsx
- src/Tab/i18n.js
> 增加 Tab 组件国际化

- src/Tab/Tab.styl
fix: Tab 组件下拉在窄分辨率下的 item 布局问题
> fix: Tab 组件下拉在窄分辨率下的 item 布局问题

- docs/Toast.md
remove duplicated onDidHide in options.
> doc(Toast) remove duplicated api

- .eslintrc.js
- src/Badge/Badge.jsx
- src/CascadeSelectField/CascadeSelectField.jsx
- src/CascadeSelectField/CascadeTab.jsx
- src/Refreshcontrol/Refreshcontrol.jsx
- src/ScrollList/ScrollList.jsx
- src/TabBar/TabBar.jsx
- src/TabBar/TabBarItemCenter.jsx
- src/TabBar/TabBarItemMore.jsx
* TabBar
* CascadeSelectField
* RefreshControl
* ScrollList
> 组件支持react16

- index.js
- src/Pagination/Pagination.jsx
- src/Table/Table.jsx
- style/component.styl
> 完成Pagination 16更新

- demo/Toast/ToastDemo.jsx
- src/Toast/Toast.jsx
- src/Toast/Toast.styl
> 加入一个新的 props 为 textWrap 让文字可以折行

- demo/ScrollList/ScrollListDemo.jsx
- demo/ScrollList/ScrollListDemo.styl
- docs/ScrollList.md
- src/ScrollList/Item.jsx
- src/ScrollList/ScrollList.jsx
- src/ScrollList/ScrollList.styl
- src/ScrollList/TagList.jsx
1. 新增人员信息缩略版
2. 新增列表信息可带徽章
3. 新增标签列表小元件
4. 更新demo & docs
> Feature/scroll list - userinfo & taglist

- demo/CheckboxField/CheckboxFieldDemo.jsx
- demo/DatetimeField/DatetimeFieldDemo.jsx
- demo/Filter/FilterDemo.jsx
- demo/PickerField/PickerFieldDemo.jsx
- demo/RadioField/RadioFieldDemo.jsx
- demo/SelectField/SelectFieldDemo.jsx
- docs/Filter.md
- src/Card/Card.styl
- src/CheckboxField/CheckboxField.jsx
- src/CheckboxField/CheckboxField.styl
- src/DatetimeField/DatetimeField.jsx
- src/Dialog/Dialog.styl
- src/Filter/Filter.jsx
- src/Filter/FilterBar.jsx
- src/Filter/FilterPanel.jsx
- src/PickerField/PickerField.jsx
- src/RadioField/RadioField.jsx
- src/SelectField/SelectField.jsx
- src/TagField/TagField.styl
- src/TextField/TextField.styl
- src/TextareaField/TextareaField.styl
> Revert "Fix style"

- demo/ScrollList/ScrollListDemo.jsx
- src/ScrollList/Item.jsx
> 增加scrolllist-onclick

- src/PhotoField/PhotoFieldFileItem.jsx
> bugfix - suffix judge

- demo/PhotoField/PhotoFieldDemo.jsx
- src/PhotoField/DdPhotoField.jsx
- src/PhotoField/PhotoField.jsx
- src/PhotoField/PhotoFieldPane.jsx
add errMsg props for photo-field
> photo-field support errMsg prop

- demo/CalendarField/CalendarFieldDemo.jsx
- src/Calendar/Calendar.jsx
- src/CalendarField/lib/DayField.jsx
支持 calendar 通过 props.visible 由外层控制显隐
> feat: calendar support props.visible

- demo/PickerField/PickerFieldDemo.jsx
- docs/Picker.md
- src/Picker/SearchPanel.jsx
- src/PickerField/PickerField.jsx
支持 picker 的 filterOption 为一个过滤函数，以自定义过滤规则。
> feat: Picker filterOption support function

- docs/Datetime.md
- src/Datetime/Datetime.jsx
- src/Datetime/util/date.js
> fix: revert pass currentValue to disabledDate and disabledTime

- demo/CascadeSelectField/CascadeSelectFieldDemo.jsx
- package.json
- src/CascadeSelectField/CascadeSelectField.jsx
- src/CascadeSelectField/CascadeTab.jsx
> feat:cascadeSelectAsync

- demo/CascadeSelectField/CascadeSelectFieldDemo.jsx
- src/CascadeSelectField/CascadeSelectField.jsx
> fix: async onChange
